version: 2
jobs:
  one:
    docker:
      - image: cimg/ruby:2.6.8
        auth:
          username: addyboy07
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspace" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  two:
    docker:
      - image: cimg/ruby:2.6.8
        auth:
          username: addyboy07
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:  echo "A more familiar hi"
      - attach_workspace:
          at: my_workspace
      - run:
          if [ 0 == 0 ]; then
            echo "Number is Even";
          else
            echo "Number is Odd";
          fi

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
